# Generated by Django 4.2.1 on 2023-05-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_country_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name_address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
