# Generated by Django 4.2.1 on 2023-06-19 14:08

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('address', '0003_address_name_address'),
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='fee in %')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='available amount')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoinProvider',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('IN_VALIDATION', 'IN_VALIDATION'), ('VALIDATED', 'VALIDATED'), ('BANNED', 'BANNED')], default='CREATED', max_length=20)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.province')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CoinExchangeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_tax', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name="seller's profit per unit sold")),
                ('available_amount', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='available amount')),
                ('coin_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_exchange', to='coin.coin')),
                ('coin_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_origin', to='coin.coin')),
                ('coin_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.coinprovider')),
            ],
            options={
                'verbose_name': 'Coin Exchange Offer',
                'unique_together': {('coin_provider', 'coin_origin', 'coin_exchange')},
            },
        ),
    ]
