# Generated by Django 4.2.1 on 2023-06-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='profile',
            name='known_addresses',
            field=models.ManyToManyField(to='address.address'),
        ),
    ]
