# Generated by Django 4.2.1 on 2023-06-16 12:45

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_beneficiary_profile_beneficiaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='beneficiaries',
            field=models.ManyToManyField(blank=True, null=True, related_name='beneficiaries', to='custom_user.beneficiary'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='phone number'),
        ),
    ]
