# Generated by Django 4.2.1 on 2023-05-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('iso_code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='iso code')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('symbol', models.CharField(max_length=3, verbose_name='symbol')),
            ],
        ),
    ]
